version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: hotel_postgres
    environment:
      POSTGRES_DB: hotel
      POSTGRES_USER: hoteluser
      POSTGRES_PASSWORD: hotelpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: hotel_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hotel
      SPRING_DATASOURCE_USERNAME: hoteluser
      SPRING_DATASOURCE_PASSWORD: hotelpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata: